### ISSUE TITLE
The benefits from multiple tables in an SQLite database:

### ISSUE THREAD

**Issue by mikeducey** [mikeducey/to-do-list_OO#1]
One question, then: as I incorporate this design in the project, I’ve done a bit of looking to see how there are different tables.  It’ll take some learning on how to write this, but I can do so (eventually!).  However, in this assignment, I wonder exactly the benefit of it for the simple structure of the current data being stored?  What is the benefit (in terms of complexity) to call an id of, say, a family member where the id stored on that table is being referenced on the table where I’ll pull my data from?  I will have a database that will have four columns: the ID, the task, and then the IDs for the family member and status of the task.  The code to pull from other tables will increase the complexity of the functions requiring the population of the ID of the family member with that IDs corresponding name (same with status).  So, as asked earlier, is the benefit of a dry database greater than the benefit of having less complex code that does not require accessing 3 tables?

**Comment by sumeetjain** [comment]
There are a couple reasons why we'd do it this way:
1. IDs are guaranteed to be unique. If two family members were both named "Stacey", there's no way at all to distinguish them in the database. By making a separate table for family members, you now have the ability to add additional columns (later), like a `user_picture` column (or something), which will let your users have identification in your application besides their name alone.
2. Related: Separate tables let you expand the information about each resource, like `user_picture`, team memberships (e.g. if users need to be grouped into teams for larger tasks), etc. You shouldn't be building this functionality right now, but preparing a clean DB design helps to avoid issues later if you want to add functionality.
3. DRYer databases help when you need to change information. If a family member's name needed to change, you have to update each row in the tasks table. That's problematic for two reasons:
   - It's semantically odd: Why are you updating a "tasks" table if a _family member_ is what's being changed? Clearly a lack of separation of concerns...
   - You're changing code in several places, instead of one. If you had the family member's name in the `family_members` table, you'd just change it there and then you're done.
