### ISSUE TITLE
How to incorporate modules without Hashes

### ISSUE THREAD

**Issue by mikeducey** [mikeducey/to-do-list_OO#3]
I asked for help generally, but after receiving the results I'm having a hard time thinking about how I might incorporate my way of incorporating the methods through the controller (and the resulting view) in a way that won't use a hash.   As is, if you look at the controller, I use params that are populated in the controller as arguments to help get (say), the tasks filtered by complete and incomplete.  I then, in the view, run "each" on those returned hashes to print the task information for each list of tasks.   If I can filter the information in the DB as I do, it's easy to pick out the particular values that I want from the hashes to display them in the view.  But I don't see how I will get the required arguments into the module's defined functions so that they return what I'm looking for:

 Here is an easy example, as it just prints the name of a family member:

In the controller : `@member = Task.print_name(params[:user])`

The corresponding method:
`def self.print_name(name)
            @selectFM = DB.prepare("SELECT name FROM name WHERE id == \"#{name}\"")
            familyMember = @selectFM.execute
        return familyMember
    end`

If I'm thinking in the module, I could have a module that might look like the following:
`def self.findByName(name)
    names = DB.execute("SELECT * FROM #{table} WHERE name == \"#{name}\"")
    name = names[0]
    Task.new(fields)
  end
`

Here are my questions (Sorry this is getting so long):
1.  Where would I put in the fields for the arguments that would go in for the #{table} and #{name}?  Would that go in the controller? Or is the function here defined in the model to be called in another function in the Task class?
2.  What would I put in place of "fields" in that Task.new line in order to get the specific object that I'd like?  The particular column name of the database? (which, in this case, would be "name"? 
3.  Say I put "Bob" in where I called this findByName function.  It should supposedly select from the right table a group of objects that have "Bob" as the name (I use ids instead of names, but for the sake of clarity here I'm using "Bob" instead of 1).  Is the idea that I put something like Task.new("task") instead of "fields" and I'll get the "tasks" from the DB? (It's a column). And I suppose I'd need to know where to put the specific info here:  I can't imagine we'd put a specific value in the module, but where we would we tell that function in the module what goes in the fields here?  It's not an argument in the function name self.findByName.  Or should I actually have more arguments, like in this case it would need to say self.findByName(table, name, fields)?  
4.  Is a module function like findByName too specific?  Should it really just be `find`?  In that case, since at times I might also want to find by id, should I make another ruby input to have an argument for the various things I want to "find by"?  so, instead of `WHERE name == \"#{name}\""` I should have `WHERE #{columnTitle} == \"#{name}\""` ?

**Comment by sumeetjain** [comment]
> Where would I put in the fields for the arguments that would go in for the #{table} and #{name}? Would that go in the controller? Or is the function here defined in the model to be called in another function in the Task class?

Short answer: Don't worry about it. Your instructions are to begin by converting your classes (e.g. the `Task` class) to be more like what we covered together in class. Specifically, your classes should have methods like the ones I define in the `User` model in my example code.

Long answer: It really depends on how you end up moving functionality from your classes (_after_ you've done the work being instructed above in the short answer) into the module. You might define a constant in each class called `TABLE_NAME`, which the module then references in its code. But there are other ways too.

---

> What would I put in place of "fields" in that Task.new line in order to get the specific object that I'd like? The particular column name of the database? (which, in this case, would be "name"?

You should have a method in your `Task` class called `Task.find`, just like I did in the example today. You'll pass a particular ID into that function to get the Task object representing that record. Your controller might end up looking like this:

``` ruby
@task = Task.find(params[:task_id])
```

If you need to display the name of the person who is assigned to that task, define a new instance method in the `Task` class so that you can call `@task.owner_name` (or something like that). So in your `Task` class, you might have this method defined:

``` ruby
def owner_name
  # Some SQL to get the name of the person who is assigned this task.
end
```

---

> Say I put "Bob" in where I called this findByName function. It should supposedly select from the right table a group of objects that have "Bob" as the name (I use ids instead of names, but for the sake of clarity here I'm using "Bob" instead of 1). Is the idea that I put something like Task.new("task") instead of "fields" and I'll get the "tasks" from the DB? (It's a column). And I suppose I'd need to know where to put the specific info here: I can't imagine we'd put a specific value in the module, but where we would we tell that function in the module what goes in the fields here? It's not an argument in the function name self.findByName. Or should I actually have more arguments, like in this case it would need to say self.findByName(table, name, fields)?

Thinking about the module is obscuring your next steps. You should abandon trying to figure out how to get the module working. You're not there yet. Stick to implementing the classes as we talked about in class, and then–when you have those working well–the module will be easier to attack.

---

> Is a module function like findByName too specific? Should it really just be find? In that case, since at times I might also want to find by id, should I make another ruby input to have an argument for the various things I want to "find by"? so, instead of WHERE name == \"#{name}\"" I should have WHERE #{columnTitle} == \"#{name}\"" ?

Perhaps. Make whatever methods for finding records that you need for your application to work (and implement the various functions I enumerated in my `User` class example).

This is where TDD shines: You define a need for some feature, like "I need to be able to get a list of tasks that are incomplete." Then you define a method in the model that might do that: `def Task.incomplete...`. Then you write a test for it and keep coding until the test passes.

Corollary: Don't write functions for features that don't exist yet (except the functions I specifically enumerated).
